### ISSUE TITLE
Boundries of image

### ISSUE THREAD

**Issue by ronnyk134** [myang-git/iOS-Image-Crop-View#12]
When showing an image from the camera there is a part of the boundary not shown in the crop view. For normal pictures this is not noticeable since your area of interest is the center, however In some cases you are interested in items on the boundary and to me this is huge problem.

**Comment by mnill** [comment]
Can you try to remove subtraction of [[self navigationController] navigationBar].bounds.size.height on 54 line of ImageCropView.m ? There is something is wrong with size calculation in app with\without navigation bar.

**Comment by mnill** [comment]
You have problem only with portrait photos?

**Comment by mnill** [comment]
There is problem with calculation size in app with\without status bar

**Comment by ronnyk134** [comment]
Yes it seem to be portrait only. However this is a problem on both the x and y axis. On the y axis the image extends beyond and under the navigation bar at the top. So it's not only the size of the navigation bar but something more fundamental.

**Comment by mnill** [comment]
Can you try out my fork. until they will be merged?

**Comment by ronnyk134** [comment]
Works like a charm. Thank you very much it has been extreml helpfull. 
Should I leave the issue open or would it be correct to merge it now ?

**Comment by mnill** [comment]
Yes, leave it opened

**Comment by myang-git** [comment]
do you have a pull request?
