### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by halpz** [myang-git/iOS-Image-Crop-View#14]
/ImageCropView.m:324:126: No member named 'x' in 'CLLocationCoordinate2D'

/ImageCropView.m:324:172: No member named 'y' in 'CLLocationCoordinate2D'

**Comment by halpz** [comment]
i changed x to longitude and y to latitude

**Comment by myang-git** [comment]
Are you referring to point.x and point .y? The type of the variable point is expected to be CGPoint, not CLLocationCoordinate2D

**Comment by seenickcode** [comment]
Still having this issue. I had to manually patch per @halpz's answer

**Comment by sssuourabh** [comment]
if (sqrt(pow((point.x-view.center.x),2) + pow((point.y-view.center.y),2))>sqrt(pow((point.x- [PointsArray[i] center].x),2) + pow((point.y- [PointsArray[i] center].y),2)))
            view = PointsArray[i];
how to get patch of this
