### ISSUE TITLE
Swift Implementation

### ISSUE THREAD

**Issue by pcs289** [myang-git/iOS-Image-Crop-View#15]
When instantiating the ```ImageCropViewController(image: myUIImage) ``` it detects the initializer as the Delegate method ```ImageCropViewController(controller: UIViewController!, didFinishCroppingImage croppedImage: UIImage!)``` so it expects the initializer to provide the ```croppedImage``` argument

**Comment by matrpedreira** [comment]
Hey, so I fixed this problem by changing the ImageCropViewControllerDelegate on the header to:
#pragma mark ImageCropViewControllerDelegate interface
@protocol ImageCropViewControllerDelegate <NSObject>

- (void)ImageCropViewController2:(UIViewController* )controller didFinishCroppingImage:(UIImage *)croppedImage;
- (void)ImageCropViewControllerDidCancel:(UIViewController *)controller;

@end

**Comment by matrpedreira** [comment]
And on the .m:
- (IBAction)done:(id)sender
{
    
    if ([self.delegate respondsToSelector:@selector(ImageCropViewController2:didFinishCroppingImage:)])
    {
        UIImage *cropped;
        if (self.image != nil){
            CGRect CropRect = self.cropView.cropAreaInImage;
            CGImageRef imageRef = CGImageCreateWithImageInRect([self.image CGImage], CropRect) ;
            cropped = [UIImage imageWithCGImage:imageRef];
            CGImageRelease(imageRef);
        }
        [self.delegate ImageCropViewController2:self didFinishCroppingImage:cropped];
    }
    
}
@end

**Comment by pcs289** [comment]
Thank you @matrpedreira, I would add ```@protocol ImageCropViewControllerDelegate <NSObject> ``` in the .h so that respondsToSelector: actually works

**Comment by matrpedreira** [comment]
Probably better, the problem is that I don't have experience with Objective-C so just tried some stuff until it worked.

**Comment by ppsdang** [comment]
Hi Currently I am facing the same issue.

**Comment by myang-git** [comment]
Do you have an example that can reproduce this issue so I can take a look?
