### ISSUE TITLE
Croping Not Working smothely 2nd Time crop the same photo

### ISSUE THREAD

**Issue by malavagile** [myang-git/iOS-Image-Crop-View#16]
Hello,

I have just implemented your library for cropping images and it's working superb when I edit the photo fist time but when I select the same photo second time to crop, the view controller appear and show the cropping screen but the box appear for selecting the image area is not move smoothly as it was working in First time cropping. Like when i try to drag the area it just stick to image bounds.

**Comment by mnill** [comment]
Could not reproduce.
In example app all works well.
May be you doing something wrong?
Could you provide example xcode project and steps to reproduce?

**Comment by malavagile** [comment]
please download the sample which I made from below link : https://drive.google.com/file/d/0Byb4VeRBzTKvaXlGMDcxX0dyNk0/view?usp=sharing

**Comment by malavagile** [comment]
I guess I found the issue, When you crop image to very small size and then you select to crop the small size image again then the behaviour is changed.

**Comment by mnill** [comment]
Issue can be there, yes.
As i known, min size to crop is set to 400x400 (i really don't know why).
Try to play around constant IMAGE_MIN_HEIGHT, IMAGE_MIN_WIDTH in ImageCropView.m.
I test with value 10x10, and all work fine.

May be we need to change default value to 10x10.

**Comment by mnill** [comment]
@malavagile any results?
