### ISSUE TITLE
Memory Not Release after Cropping 

### ISSUE THREAD

**Issue by JayMehta711** [myang-git/iOS-Image-Crop-View#40]
Hello , I have used Image Crop View Classes in Base project after croping image and save image that release memory but in My Project it not release memory every time it will increase memory. I have tested in Iphone 4s. Can you please help me out anyone ?

-(void)OpenImageCropViewController:(UIImage *)imageObj
{
    ImageCropViewController *controller = [[ImageCropViewController alloc] initWithImage:imageObj];
    controller.delegate = self;
    controller.blurredBackground = NO;
    [[self navigationController] pushViewController:controller animated:NO];
}

#pragma mark - IMAGECROP VIEWCONTROLLER DELEGATE METHOD
- (void)ImageCropViewControllerSuccess:(ImageCropViewController *)controller didFinishCroppingImage:(UIImage *)croppedImage{
    
    //imgCurrDoc  = croppedImage;
    
    NSLog(@"ViewControllers %@",[self navigationController].viewControllers);
    [[self navigationController] popViewControllerAnimated:YES];
    NSLog(@"AFTER ViewControllers %@",[self navigationController].viewControllers);
    [self createDocumentViewsWithImage:croppedImage];
    [self showBottomBar_DOCVC];
    
    
    controller.delegate = nil;
    controller = nil;
}

- (void)ImageCropViewControllerDidCancel:(ImageCropViewController *)controller{
    
    NSLog(@"ViewControllers %@",[self navigationController].viewControllers);
    [[self navigationController] popViewControllerAnimated:YES];
    NSLog(@"AFTER ViewControllers %@",[self navigationController].viewControllers);
    controller.delegate = nil;
    controller = nil;
}

**Comment by myang-git** [comment]
Let me take a look. What is your xcode version?
